### PostSpawner 配置文件 ###

# 更新检查设置
update-checker:
  # 是否启用更新检查
  enabled: true
  # 检查频率（天）
  check-interval-days: 1

# 语言设置 (目前支持: zh_CN, en_US)
language: zh_CN

# 刷怪笼挖掘设置
spawner:
  # 基础挖掘失败的概率 (0.0-1.0)
  fail-chance: 0.7
  
  # 使用精准采集工具时减少的失败概率 (0.0-1.0)
  # 例如：基础失败率0.7，精准采集减少0.2，则使用精准采集时失败率为0.5
  silk-touch-bonus: 0.2
  
  # 刷怪笼物品显示名称格式（%entity_type% 会被替换为实体类型）
  display-name: "&f%entity_type% &7刷怪笼"
  
  # 刷怪笼物品lore格式（%entity_type% 会被替换为实体类型）
  lore: "&7实体类型: &f%entity_type%"
  
  # 额外的lore行（可选）
  additional-lore:
    - "&7由 &3Post&bSpawner &7提供"
    - "&7右键放置"
  
  # 挖掘成功时执行的动作
  success-actions:
    - "[message] &a成功挖掘了刷怪笼！"
    - "[sound] BLOCK_NOTE_BLOCK_PLING 1.0 1.0"
    - "[drop_monster_spawner]"

  # 挖掘失败时执行的动作
  fail-actions:
    - "[message] &c挖掘刷怪笼失败！"
    - "[sound] BLOCK_ANVIL_LAND 1.0 1.0"
    - "[buff] MINING_FATIGUE 10 1"
    - "[title] &c挖掘失败 &7刷怪笼碎裂了"

  # 当玩家使用精准采集工具挖掘刷怪笼时执行的动作
  silk-touch-actions:
    - "[message] &b你使用了精准采集工具挖掘刷怪笼！"
    - "[sound] ENTITY_EXPERIENCE_ORB_PICKUP 1.0 1.5"
    - "[buff] SPEED 10 1"

# 调试模式
debug: false
